language: shell
os: windows
env: PATH="/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/bin:$PATH"
install:
  - choco install nuget.commandline
  - nuget restore Src/HRM/HRM.sln
  - choco install xunit
script:
  - ./build.bat
  - xunit.console ./Src/HRM/HRMUnitTests/bin/Release/HRMUnitTests.dll
